### ISSUE TITLE
Default tutorial results in committing secrets to git

### ISSUE THREAD

**Issue by davidebbo** [arafato/funcy-azure#2]
Following through tutorial, it starts by creating a project that has the secrets in `admin.env`. It then says to create a git repo, but the `.gitignore` doesn't ignore `admin.env`.

Probably need to find some alternate flow to deal with secrets so they don't end up in repo.

**Comment by arafato** [comment]
This is strange. `project create` creates a `.gitignore` file which includes `admin.env`. Can you confirm that this entry hasn't been created? The end of this file should contain the following files

```
# Funcy Azure
local.env
cloud.env
admin.env
lib/node_modules
```

Thanks!

**Comment by davidebbo** [comment]
Duh, I used a batch files to bring in a license file and forgot that this also overwrites the .gitignore. Basically, pebkac :)
